Concept 1 :-  Generating 3 different matrix with only one single matrix data

In [2]:
import torch
import numpy
import torch.nn as nn
import torch.nn.functional as F

In [4]:
class Concept1(nn.Module):
    def __init__(self, emb_dim):
        super().__init__()
        self.embdim = emb_dim
        self.k = nn.Linear(emb_dim,emb_dim)
        self.q = nn.Linear(emb_dim,emb_dim)
        self.v = nn.Linear(emb_dim,emb_dim)

    def forward(self,x):
        k = self.k(x)
        q = self.q(x)
        v = self.v(x)
        print(k)
        print(q)
        print(v)


a = torch.randn(6, 5)
b = torch.tensor(a, requires_grad=True)

c1 = Concept1(emb_dim=b.shape[-1])
c1(b)

tensor([[-0.4251,  0.4382,  0.3007,  0.3169,  0.8361],
        [ 0.3076,  0.2251,  1.2821,  0.6387, -0.6614],
        [ 0.8434,  1.0309, -0.1368, -0.3322,  0.0446],
        [ 0.2804, -0.0390,  1.0247,  0.7031, -1.3931],
        [ 0.0178, -0.0484,  0.3412,  1.0037,  0.1106],
        [ 0.3061,  0.5738, -0.2052,  0.1140,  0.5601]],
       grad_fn=<AddmmBackward0>)
tensor([[ 0.2106,  0.5981,  0.9899, -0.5624, -0.8608],
        [ 0.0428,  0.2853, -0.0715, -0.4013,  0.8694],
        [-0.7615, -0.4977, -1.0247, -0.1475,  0.6609],
        [-0.1677,  0.9089, -0.2905, -1.8193, -0.0843],
        [ 1.0597,  0.6157,  0.1083, -0.2329,  0.1097],
        [ 0.1666,  0.0808, -0.1704, -0.0370,  0.0958]],
       grad_fn=<AddmmBackward0>)
tensor([[-0.6743, -0.1719,  1.1816, -0.8160, -1.2085],
        [-0.5060,  0.1662,  0.7525,  0.1128, -1.2665],
        [ 1.1471,  1.1121, -0.6207,  1.2654, -0.4611],
        [ 0.9681,  0.4220,  0.9354,  0.6982, -0.8454],
        [-1.0337, -0.7516,  0.2145, -0.3838, -0.3424

C:\Users\goura\AppData\Local\Temp\ipykernel_22096\3350324195.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(a, requires_grad=True)


concept :-
matmul(v,softmax(matrixmul(k,qT)/scaler))

In [ ]:
class SelfAttention(nn.Module):
    def __init__(self, emb_dim):
        super().__init__()
        self.embdim = emb_dim
        self.k = nn.Linear(emb_dim,emb_dim)
        self.q = nn.Linear(emb_dim,emb_dim)
        self.v = nn.Linear(emb_dim,emb_dim)

    def forward(self,x):
        k = self.k(x)
        q = self.q(x)
        v = self.v(x)
        scaler = self.embdim
        s1 = q @ k.transpose(-1,-2)/(scaler**0.5)
        att = F.softmax(s1,dim=-1)
        out = att @ v
        return out, att

a = torch.randn(6, 5)
b = torch.tensor(a, requires_grad=True)

attention = SelfAttention(emb_dim=b.shape[-1])
out , att = attention(b)
print(out)
print(att)


tensor([[-2.8464e-01,  2.9192e-01, -7.2281e-02, -3.6686e-02, -1.8612e-03,
          4.9618e-02,  4.8497e-01,  1.5501e-01,  3.7335e-01,  7.6523e-02,
         -3.2601e-01, -3.3364e-01, -1.9043e-01, -7.3444e-02,  3.0483e-01,
         -8.9185e-02,  5.3117e-02,  1.6729e-01,  2.4238e-01, -3.4038e-01,
          1.6369e-01,  2.3353e-02, -1.1501e-01, -1.4158e-01, -2.2434e-01,
          3.7792e-01,  8.1843e-02,  8.5872e-03,  9.4207e-02,  1.3596e-02,
          2.8717e-01,  3.1241e-01, -3.7534e-01,  2.2513e-01,  4.1313e-02,
          3.7895e-01,  2.1481e-01,  5.3027e-01,  2.0858e-01,  1.2127e-01,
          1.4616e-01,  7.5241e-02, -2.3973e-01, -2.4743e-01, -3.1431e-01,
          2.5668e-01, -1.6474e-01, -4.7860e-01,  1.9408e-01, -5.9220e-02,
         -2.3748e-01, -1.9110e-01, -2.4003e-01, -1.4588e-01, -2.7533e-01,
          3.8663e-02, -3.4679e-02,  1.3224e-01, -8.4317e-02,  4.2258e-01,
         -4.3606e-01, -9.6355e-02, -1.0799e-02, -1.7911e-02,  3.2445e-01,
         -1.4370e-01,  4.6965e-02, -2.

C:\Users\goura\AppData\Local\Temp\ipykernel_22096\2283042261.py:20: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(a, requires_grad=True)


there can my many context of single sentance multihead allow to extract more than one context -> n head = n context